"""add about and last time seen

Revision ID: 981ecdba7351
Revises: ab30c114ca51
Create Date: 2018-09-23 19:57:06.955440

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '981ecdba7351'
down_revision = 'ab30c114ca51'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('about_me', sa.String(length=140), nullable=True))
    op.add_column('users', sa.Column('last_seen', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'last_seen')
    op.drop_column('users', 'about_me')
    # ### end Alembic commands ###
